# Generated by Django 5.1.7 on 2025-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='posterUploadFile_url',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster_url',
            new_name='posterUrl',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='releaseDate',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='releaseYear',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='video',
            new_name='videoUploadFile_url',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='video_url',
            new_name='videoUrl',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
